### ISSUE TITLE
Duplicate Opcode for Unsubscribe and Signal

### ISSUE THREAD

**Issue by Nerixyz** [SevenTV/Common#21]
Both `OpcodeUnsubscribe` and `OpcodeSignal` have the same value. This doesn't seem to be intentional.

https://github.com/SevenTV/Common/blob/3aca948a744c0ea7fc7fd3531aed1cb9e25d164c/events/events.go#L78-L79

**Comment by AnatoleAM** [comment]
Good catch thank you. Could you make a pull request changing `OpcodeSignal` from `36` to `37`?

**Comment by Nerixyz** [comment]
Sure
